version: '3.8'

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  node:
    build:
      context: node
    image: tadeucs/nginx-node-mysql:latest
    container_name: node
    tty: true
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: nodedb
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mysql
    volumes:
      - ./node:/usr/src/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge